[package]
name = "scintia-96"
version = "0.3.0"
edition = "2024"
authors = ["Sarun Rattanasiri"]
description = "A lightweight, keyed 96-bit permutation based on the Speck cipher, designed for unique ID derivation."
license = "BSD-2-Clause"
readme = "README.md"
repository = "https://github.com/midnight-wonderer/scintia-96"
keywords = ["scintia-96", "cryptography", "permutation", "no_std", "speck"]
categories = ["cryptography", "no-std", "embedded"]

[dependencies]
cipher = { version = "0.4", optional = true }

[features]
default = []
cipher = ["dep:cipher"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
